<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Power.Weather.Application\Power.Weather.Application.csproj" />
    <ProjectReference Include="..\Power.Weather.Infrastructure\Power.Weather.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
