<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Power.Weather.Web\Power.Weather.Web.csproj" />
    <ProjectReference Include="..\..\src\Power.Weather.Infrastructure\Power.Weather.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
